### ISSUE TITLE
Console becomes unresponsive after service/table view

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/gilligan#5]
Running console against https://github.com/skupperproject/skupper-example-mongodb-replica-set. Navigated to service table view and selected mongo-a service. Console became unresponsive and could not navigate from view. 

![mongo-a-svc-wait](https://user-images.githubusercontent.com/4321852/107648445-54bd3d80-6c4a-11eb-9fd3-3c7febdc3467.png)

**Comment by ajssmith** [comment]
I could not get the console to recover, this is what /DATA returned:
======================================================================
{
    "sites": [
        {
            "site_name": "public1",
            "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7",
            "version": "51fdfc9-modified",
            "connected": [],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.apps.ansmith-van11.rhmw-integrations.net",
            "edge": false
        },
        {
            "site_name": "public2",
            "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5",
            "version": "51fdfc9-modified",
            "connected": [
                "5316d5e6-43af-4755-acea-fee0107d6fb7"
            ],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.apps.ansmith-van15.rhmw-integrations.net",
            "edge": false
        },
        {
            "site_name": "private1",
            "site_id": "70f1914e-7ff0-4199-ad97-f3670a681c0b",
            "version": "51fdfc9-modified",
            "connected": [
                "5316d5e6-43af-4755-acea-fee0107d6fb7",
                "3914b0cf-16a2-43fc-b22e-e01de55719c5"
            ],
            "namespace": "default",
            "url": "10.111.31.223",
            "edge": false
        }
    ],
    "services": [
        {
            "address": "mongo-c",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-c-d69cbc956-n7qlr",
                    "target": "mongo-c",
                    "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7",
                    "connections": {
                        "10.129.2.91:38940@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:38940@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5009,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 593274,
                            "bytes_out": 1015890,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:40026@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:40026@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4,
                            "last_in": 4859,
                            "bytes_in": 365,
                            "bytes_out": 390168,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:40040@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:40040@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 8,
                            "last_in": 8,
                            "bytes_in": 29646,
                            "bytes_out": 67901,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        }
                    }
                },
                {
                    "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5",
                    "connections": {
                        "10.128.2.74:46976@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:46976@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 7,
                            "last_in": 4866,
                            "bytes_in": 365,
                            "bytes_out": 390168,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:46978@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:46978@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 29707,
                            "bytes_out": 68039,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        }
                    }
                },
                {
                    "site_id": "70f1914e-7ff0-4199-ad97-f3670a681c0b",
                    "connections": {
                        "172.17.0.3:42590@70f1914e-7ff0-4199-ad97-f3670a681c0b": {
                            "id": "172.17.0.3:42590@70f1914e-7ff0-4199-ad97-f3670a681c0b",
                            "start_time": 5003,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 607997,
                            "bytes_out": 1036783,
                            "client": "mongo-a-8587696489-jwn6z"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5",
                    "connections": {
                        "10.128.2.74:46976@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:46976@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 4866,
                            "last_in": 7,
                            "bytes_in": 390168,
                            "bytes_out": 758,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:46978@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:46978@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 68039,
                            "bytes_out": 30100,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.129.2.91:38940@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:38940@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5015,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 1016324,
                            "bytes_out": 593921,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.129.2.91:40026@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:40026@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4865,
                            "last_out": 4865,
                            "last_in": 5,
                            "bytes_in": 390168,
                            "bytes_out": 758,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.129.2.91:40040@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:40040@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4865,
                            "last_out": 9,
                            "last_in": 9,
                            "bytes_in": 67901,
                            "bytes_out": 30039,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        },
                        "172.17.0.3:42590@70f1914e-7ff0-4199-ad97-f3670a681c0b": {
                            "id": "172.17.0.3:42590@70f1914e-7ff0-4199-ad97-f3670a681c0b",
                            "start_time": 5004,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 1036783,
                            "bytes_out": 608390,
                            "server": "mongo-c-d69cbc956-n7qlr"
                        }
                    }
                }
            ]
        },
        {
            "address": "mongo-b",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-b-6866c58b8d-lsvd5",
                    "target": "mongo-b",
                    "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7",
                    "connections": {
                        "10.129.2.91:49170@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49170@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4,
                            "last_in": 4860,
                            "bytes_in": 416,
                            "bytes_out": 390623,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49174@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49174@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4,
                            "last_in": 4860,
                            "bytes_in": 253,
                            "bytes_out": 389575,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49180@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49180@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 9,
                            "last_in": 9,
                            "bytes_in": 29646,
                            "bytes_out": 67901,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        }
                    }
                },
                {
                    "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5",
                    "connections": {
                        "10.128.2.74:37366@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37366@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5015,
                            "last_out": 0,
                            "last_in": 1,
                            "bytes_in": 598410,
                            "bytes_out": 1018899,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:38422@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38422@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 29880,
                            "bytes_out": 68770,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:38436@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38436@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 5,
                            "last_in": 4866,
                            "bytes_in": 192,
                            "bytes_out": 389437,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        }
                    }
                },
                {
                    "site_id": "70f1914e-7ff0-4199-ad97-f3670a681c0b",
                    "connections": {
                        "172.17.0.3:47404@70f1914e-7ff0-4199-ad97-f3670a681c0b": {
                            "id": "172.17.0.3:47404@70f1914e-7ff0-4199-ad97-f3670a681c0b",
                            "start_time": 5003,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 610945,
                            "bytes_out": 1043563,
                            "client": "mongo-a-8587696489-jwn6z"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7",
                    "connections": {
                        "10.128.2.74:37366@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37366@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5009,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 1018465,
                            "bytes_out": 598547,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.128.2.74:38422@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38422@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4861,
                            "last_out": 9,
                            "last_in": 9,
                            "bytes_in": 68632,
                            "bytes_out": 30212,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.128.2.74:38436@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38436@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4860,
                            "last_out": 4860,
                            "last_in": 4,
                            "bytes_in": 389437,
                            "bytes_out": 585,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49170@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49170@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4860,
                            "last_in": 4,
                            "bytes_in": 390623,
                            "bytes_out": 809,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49174@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49174@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4860,
                            "last_in": 4,
                            "bytes_in": 389575,
                            "bytes_out": 646,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49180@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49180@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 9,
                            "last_in": 9,
                            "bytes_in": 67901,
                            "bytes_out": 30039,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "172.17.0.3:47404@70f1914e-7ff0-4199-ad97-f3670a681c0b": {
                            "id": "172.17.0.3:47404@70f1914e-7ff0-4199-ad97-f3670a681c0b",
                            "start_time": 4999,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 1043129,
                            "bytes_out": 610690,
                            "server": "mongo-b-6866c58b8d-lsvd5"
                        }
                    }
                }
            ]
        },
        {
            "address": "mongo-a",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-a-8587696489-jwn6z",
                    "target": "mongo-a",
                    "site_id": "70f1914e-7ff0-4199-ad97-f3670a681c0b"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "5316d5e6-43af-4755-acea-fee0107d6fb7",
                    "connections": {
                        "10.129.2.91:46366@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46366@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5008,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 732748,
                            "bytes_out": 490355,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:46462@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46462@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4998,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 605870,
                            "bytes_out": 994436,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:46466@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46466@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4997,
                            "last_out": 2,
                            "last_in": 4997,
                            "bytes_in": 699,
                            "bytes_out": 808132,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:47434@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:47434@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 4,
                            "last_in": 4860,
                            "bytes_in": 363,
                            "bytes_out": 401862,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:47452@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:47452@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4860,
                            "last_out": 9,
                            "last_in": 9,
                            "bytes_in": 29646,
                            "bytes_out": 67925,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49552@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49552@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4561,
                            "last_out": 4561,
                            "last_in": 4561,
                            "bytes_in": 340,
                            "bytes_out": 839,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        },
                        "10.129.2.91:49554@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49554@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4561,
                            "last_out": 4561,
                            "last_in": 4561,
                            "bytes_in": 0,
                            "bytes_out": 839,
                            "client": "mongo-b-6866c58b8d-lsvd5"
                        }
                    }
                },
                {
                    "site_id": "3914b0cf-16a2-43fc-b22e-e01de55719c5",
                    "connections": {
                        "10.128.2.74:37816@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37816@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5014,
                            "last_out": 3,
                            "last_in": 3,
                            "bytes_in": 729373,
                            "bytes_out": 489712,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:37894@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37894@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5004,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 608768,
                            "bytes_out": 991534,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:37900@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37900@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5003,
                            "last_out": 3,
                            "last_in": 5003,
                            "bytes_in": 702,
                            "bytes_out": 1080176,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:38868@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38868@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 6,
                            "last_in": 4866,
                            "bytes_in": 363,
                            "bytes_out": 401863,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:38876@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38876@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4866,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 29707,
                            "bytes_out": 68063,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:40960@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:40960@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4566,
                            "last_out": 4566,
                            "last_in": 4566,
                            "bytes_in": 0,
                            "bytes_out": 839,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        },
                        "10.128.2.74:40962@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:40962@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4566,
                            "last_out": 4566,
                            "last_in": 4566,
                            "bytes_in": 0,
                            "bytes_out": 839,
                            "client": "mongo-c-d69cbc956-n7qlr"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "70f1914e-7ff0-4199-ad97-f3670a681c0b",
                    "connections": {
                        "10.128.2.74:37816@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37816@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5012,
                            "last_out": 4,
                            "last_in": 4,
                            "bytes_in": 489712,
                            "bytes_out": 729766,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:37894@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37894@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5002,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 991534,
                            "bytes_out": 609161,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:37900@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:37900@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 5001,
                            "last_out": 5001,
                            "last_in": 4,
                            "bytes_in": 1080176,
                            "bytes_out": 1083,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:38868@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38868@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4864,
                            "last_out": 4864,
                            "last_in": 7,
                            "bytes_in": 401863,
                            "bytes_out": 756,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:38876@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:38876@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4864,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 68063,
                            "bytes_out": 30100,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:40960@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:40960@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4565,
                            "last_out": 4565,
                            "last_in": 4565,
                            "bytes_in": 839,
                            "bytes_out": 340,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.128.2.74:40962@3914b0cf-16a2-43fc-b22e-e01de55719c5": {
                            "id": "10.128.2.74:40962@3914b0cf-16a2-43fc-b22e-e01de55719c5",
                            "start_time": 4565,
                            "last_out": 4565,
                            "last_in": 4565,
                            "bytes_in": 839,
                            "bytes_out": 340,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:46366@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46366@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5012,
                            "last_out": 4,
                            "last_in": 4,
                            "bytes_in": 490355,
                            "bytes_out": 733141,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:46462@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46462@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5002,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 994852,
                            "bytes_out": 606517,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:46466@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:46466@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 5001,
                            "last_out": 5001,
                            "last_in": 5,
                            "bytes_in": 808132,
                            "bytes_out": 1080,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:47434@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:47434@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4864,
                            "last_out": 4864,
                            "last_in": 7,
                            "bytes_in": 401862,
                            "bytes_out": 756,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:47452@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:47452@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4864,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 68063,
                            "bytes_out": 30100,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:49552@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49552@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4564,
                            "last_out": 4564,
                            "last_in": 4564,
                            "bytes_in": 839,
                            "bytes_out": 340,
                            "server": "mongo-a-8587696489-jwn6z"
                        },
                        "10.129.2.91:49554@5316d5e6-43af-4755-acea-fee0107d6fb7": {
                            "id": "10.129.2.91:49554@5316d5e6-43af-4755-acea-fee0107d6fb7",
                            "start_time": 4564,
                            "last_out": 4564,
                            "last_in": 4564,
                            "bytes_in": 839,
                            "bytes_out": 340,
                            "server": "mongo-a-8587696489-jwn6z"
                        }
                    }
                }
            ]
        }
    ]
}

**Comment by ErnieAllen** [comment]
This should be fixed with commit 8f44536dabc95094ddd6a46a77e6744baabd1bac to Gilligan
@ajssmith can you verify and close/update this issue?

**Comment by ajssmith** [comment]
Verified this is fixed with above commit
