### ISSUE TITLE
Console becomes unresponsive when nav from services to sites

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/gilligan#6]
May be related to #5 but console became unresponsive when navigating from services to sites view. The /DATA returned was the following:

{
    "sites": [
        {
            "site_name": "public2",
            "site_id": "00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
            "version": "51fdfc9-modified",
            "connected": [
                "8cb324d6-d356-4a20-a417-4a32b836d4b2"
            ],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.apps.ansmith-van15.rhmw-integrations.net",
            "edge": false
        },
        {
            "site_name": "private1",
            "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
            "version": "51fdfc9-modified",
            "connected": [
                "8cb324d6-d356-4a20-a417-4a32b836d4b2",
                "00cc041e-ab05-47ef-8531-6b3c7c5b92a4"
            ],
            "namespace": "skupper",
            "url": "10.103.14.185",
            "edge": false
        },
        {
            "site_name": "public1",
            "site_id": "8cb324d6-d356-4a20-a417-4a32b836d4b2",
            "version": "51fdfc9-modified",
            "connected": [],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.apps.ansmith-van11.rhmw-integrations.net",
            "edge": false
        }
    ],
    "services": [
        {
            "address": "mongo-c",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-c-d69cbc956-5xtgf",
                    "target": "mongo-c",
                    "site_id": "00cc041e-ab05-47ef-8531-6b3c7c5b92a4"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                    "connections": {
                        "172.17.0.5:58524@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "172.17.0.5:58524@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 146,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 18259,
                            "bytes_out": 32205,
                            "client": "mongo-a-8587696489-2dc7g"
                        }
                    }
                },
                {
                    "site_id": "8cb324d6-d356-4a20-a417-4a32b836d4b2",
                    "connections": {
                        "10.129.2.105:35894@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:35894@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 157,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 21526,
                            "bytes_out": 37654,
                            "client": "mongo-b-6866c58b8d-gphzc"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                    "connections": {
                        "10.129.2.105:35894@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:35894@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 155,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 37218,
                            "bytes_out": 21663,
                            "server": "mongo-c-d69cbc956-5xtgf"
                        },
                        "172.17.0.5:58524@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "172.17.0.5:58524@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 145,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 32205,
                            "bytes_out": 18652,
                            "server": "mongo-c-d69cbc956-5xtgf"
                        }
                    }
                }
            ]
        },
        {
            "address": "mongo-b",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-b-6866c58b8d-gphzc",
                    "target": "mongo-b",
                    "site_id": "8cb324d6-d356-4a20-a417-4a32b836d4b2"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                    "connections": {
                        "10.128.2.77:58648@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:58648@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 155,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 20975,
                            "bytes_out": 36385,
                            "client": "mongo-c-d69cbc956-5xtgf"
                        }
                    }
                },
                {
                    "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                    "connections": {
                        "172.17.0.5:58436@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "172.17.0.5:58436@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 146,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 18194,
                            "bytes_out": 31600,
                            "client": "mongo-a-8587696489-2dc7g"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "8cb324d6-d356-4a20-a417-4a32b836d4b2",
                    "connections": {
                        "10.128.2.77:58648@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:58648@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 156,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 36821,
                            "bytes_out": 21626,
                            "server": "mongo-b-6866c58b8d-gphzc"
                        },
                        "172.17.0.5:58436@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "172.17.0.5:58436@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 147,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 32036,
                            "bytes_out": 18844,
                            "server": "mongo-b-6866c58b8d-gphzc"
                        }
                    }
                }
            ]
        },
        {
            "address": "mongo-a",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "mongo-a-8587696489-2dc7g",
                    "target": "mongo-a",
                    "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0"
                }
            ],
            "connections_ingress": [
                {
                    "site_id": "00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                    "connections": {
                        "10.128.2.77:39360@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39360@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 154,
                            "last_out": 5,
                            "last_in": 5,
                            "bytes_in": 24246,
                            "bytes_out": 17608,
                            "client": "mongo-c-d69cbc956-5xtgf"
                        },
                        "10.128.2.77:39444@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39444@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 144,
                            "last_out": 0,
                            "last_in": 0,
                            "bytes_in": 18008,
                            "bytes_out": 30084,
                            "client": "mongo-c-d69cbc956-5xtgf"
                        },
                        "10.128.2.77:39458@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39458@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 144,
                            "last_out": 5,
                            "last_in": 143,
                            "bytes_in": 708,
                            "bytes_out": 25543,
                            "client": "mongo-c-d69cbc956-5xtgf"
                        }
                    }
                },
                {
                    "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                    "connections": {
                        "192.168.39.1:53380@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "192.168.39.1:53380@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 178,
                            "last_out": 95,
                            "last_in": 95,
                            "bytes_in": 2970,
                            "bytes_out": 13183,
                            "client": "192.168.39.1"
                        }
                    }
                },
                {
                    "site_id": "8cb324d6-d356-4a20-a417-4a32b836d4b2",
                    "connections": {
                        "10.129.2.105:50872@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50872@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 156,
                            "last_out": 1,
                            "last_in": 2,
                            "bytes_in": 23814,
                            "bytes_out": 17285,
                            "client": "mongo-b-6866c58b8d-gphzc"
                        },
                        "10.129.2.105:50956@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50956@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 146,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 18096,
                            "bytes_out": 30479,
                            "client": "mongo-b-6866c58b8d-gphzc"
                        },
                        "10.129.2.105:50968@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50968@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 145,
                            "last_out": 2,
                            "last_in": 145,
                            "bytes_in": 712,
                            "bytes_out": 32295,
                            "client": "mongo-b-6866c58b8d-gphzc"
                        }
                    }
                }
            ],
            "connections_egress": [
                {
                    "site_id": "d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                    "connections": {
                        "10.128.2.77:39360@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39360@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 155,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 17933,
                            "bytes_out": 25115,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "10.128.2.77:39444@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39444@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 145,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 30084,
                            "bytes_out": 18401,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "10.128.2.77:39458@00cc041e-ab05-47ef-8531-6b3c7c5b92a4": {
                            "id": "10.128.2.77:39458@00cc041e-ab05-47ef-8531-6b3c7c5b92a4",
                            "start_time": 145,
                            "last_out": 144,
                            "last_in": 1,
                            "bytes_in": 26225,
                            "bytes_out": 1089,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "10.129.2.105:50872@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50872@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 155,
                            "last_out": 1,
                            "last_in": 1,
                            "bytes_in": 17285,
                            "bytes_out": 24207,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "10.129.2.105:50956@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50956@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 145,
                            "last_out": 2,
                            "last_in": 2,
                            "bytes_in": 30479,
                            "bytes_out": 18489,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "10.129.2.105:50968@8cb324d6-d356-4a20-a417-4a32b836d4b2": {
                            "id": "10.129.2.105:50968@8cb324d6-d356-4a20-a417-4a32b836d4b2",
                            "start_time": 144,
                            "last_out": 144,
                            "last_in": 1,
                            "bytes_in": 32295,
                            "bytes_out": 1093,
                            "server": "mongo-a-8587696489-2dc7g"
                        },
                        "192.168.39.1:53380@d6916a5f-3a65-4b17-9c07-73adcfbb0db0": {
                            "id": "192.168.39.1:53380@d6916a5f-3a65-4b17-9c07-73adcfbb0db0",
                            "start_time": 178,
                            "last_out": 95,
                            "last_in": 95,
                            "bytes_in": 13183,
                            "bytes_out": 2970,
                            "server": "mongo-a-8587696489-2dc7g"
                        }
                    }
                }
            ]
        }
    ]
}

**Comment by ErnieAllen** [comment]
This should be fixed with commit 8f44536dabc95094ddd6a46a77e6744baabd1bac to Gilligan
@ajssmith can you verify and close/update this issue?

**Comment by ajssmith** [comment]
Verified this is fixed with above commit. Thanks.
