### ISSUE TITLE
Side effect when skupper isn't feeding data

### ISSUE THREAD

**Issue by pwright** [skupperproject/gilligan#7]
Not sure what is wrong with my skupper network, but hello world seems to work fine until I log into console. Then I see 
![image](https://user-images.githubusercontent.com/5154224/107984562-144e1e80-6fc0-11eb-8bac-a91fdc5d2b7d.png)

I was expecting to see east/west. 
Changing the console url to include /data returned links to two json files

![image](https://user-images.githubusercontent.com/5154224/107984835-be2dab00-6fc0-11eb-93cc-9d8416442dbd.png)

The contents exactly match:

https://skupper-controller-west.apps-crc.testing/data/DATA.json
https://github.com/skupperproject/gilligan/blob/master/public/data/sample2.json

**Comment by pwright** [comment]
Note: when creating the issue, I got no response from /DATA
Also, I was using 'skupper' cli build from master.

**Comment by ErnieAllen** [comment]
Fixed
